version: "3.5"

volumes:
  adhole:
    name: adhole

services:
  squid:
    image: sameersbn/squid
    container_name: squid
    ports:
      - 3128:3128
    volumes:
      - adhole:/var/spool/squid
      - ./squid/squid.conf:/etc/squid/squid.conf
    networks:
      adhole:
        ipv4_address: 172.26.0.2
    depends_on:
      - pihole

  pihole:
    image: pihole/pihole
    container_name: pihole
    ports:
      - 53/tcp
      - 53/udp
      - 7777:80/tcp
#      - 443/tcp
    environment:
      ServerIP: 127.0.0.1
    volumes:
      - ./pihole:/etc/pihole
      - ./dnsmasq:/etc/dnsmasq.d
      - ./pihole-logs:/var/log/pihole
      - ./lighttpd-logs:/var/log/lighttpd
    restart: unless-stopped
    networks:
      adhole:
        ipv4_address: 172.26.0.3

networks:
  adhole:
    name: adhole
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.26.0.0/16 
